apiVersion: batch/v1
kind: CronJob
metadata:
  name: lightwing-ingest-price-list-{{ lower ( randAlphaNum 6 ) }}
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    {{- include "lwd.labels" . | nindent 4 }}
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      parallelism: 1
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: lightwing-ingest-price-list
            image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
            command: ["lwd", "ingest-price-list", "--verbose"]
            env:
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.postgresPassword.name }}
                    key: {{ .Values.postgresPassword.key }}
              - name: LIGHTWING_DB_CONNECTION
                value: "host=postgres.{{ .Release.Namespace }}.svc.cluster.local user=postgres password=$(DB_PASSWORD) dbname=postgres sslmode=disable"
              - name: FAKTORY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.faktoryPassword }}
              - name: FAKTORY_URL
                value: tcp://$(FAKTORY_PASSWORD):@lwd-faktory.{{ .Release.Namespace }}.svc.cluster.local:7419
              - name: LIGHTWING_CACHE_ADDR
                value: {{ .Values.redisUrl }}
              - name: LIGHTWING_AWSMASTER_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingAwsmasterAccessKey }}
              - name: LIGHTWING_AWSMASTER_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingAwsmasterSecretKey }}
              - name: LIGHTWING_AWSMASTER_REGION
                value: {{ .Values.aws.region }}
              - name: LIGHTWING_CLOUD-CONNECTOR_TYPE
                value: "harness"
              - name: LIGHTWING_CLOUD-CONNECTOR_REMOTE_HOST
                value: {{ .Values.global.loadbalancerURL }}
              - name: LIGHTWING_CLOUD-CONNECTOR_CONNECTOR_DETAILS_ROUTE
                value: ng/api/connectors/%s?accountIdentifier=%s
              - name: LIGHTWING_CLOUD-CONNECTOR_IDENTITY_SERVICE_SECRET
                value: HVSKUYqD4e5Rxu12hFDdCJKGM64sxgEynvdDhaOHaTHhwwn0K4Ttr0uoOxSsEVYNrUU=
              - name: LIGHTWING_CLOUD-CONNECTOR_AZURE_CLIENT_ID
                value: {{ .Values.azure.clientId }}
              - name: LIGHTWING_CLOUD-CONNECTOR_AZURE_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingCloudConnectorAzureClientSecret }}
              - name: LIGHTWING_CLOUD-CONNECTOR_REMOTE_API_TOKEN_SECRET
                value: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
              - name: LIGHTWING_METRICS_SEGMENT
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingMetricsSegment }}
              - name: LIGHTWING_AWS-GOV-MASTER_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingAwsGovmasterAccessKey }}
              - name: LIGHTWING_AWS-GOV-MASTER_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingAwsGovmasterSecretKey }}
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: lightwing-compute-savings-{{ lower ( randAlphaNum 6 ) }}
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    {{- include "lwd.labels" . | nindent 4 }}
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      parallelism: 1
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: lightwing-compute-svaings
            image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
            command: ["lwd", "compute-savings", "--verbose"]
            env:
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.postgresPassword.name }}
                    key: {{ .Values.postgresPassword.key }}
              - name: LIGHTWING_DB_CONNECTION
                value: "host=postgres.{{ .Release.Namespace }}.svc.cluster.local user=postgres password=$(DB_PASSWORD) dbname=postgres sslmode=disable"
              - name: FAKTORY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.faktoryPassword }}
              - name: FAKTORY_URL
                value: tcp://$(FAKTORY_PASSWORD):@lwd-faktory.{{ .Release.Namespace }}.svc.cluster.local:7419
              - name: LIGHTWING_CACHE_ADDR
                value: {{ .Values.redisUrl }}
              - name: LIGHTWING_AWSMASTER_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingAwsmasterAccessKey }}
              - name: LIGHTWING_AWSMASTER_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingAwsmasterSecretKey }}
              - name: LIGHTWING_AWSMASTER_REGION
                value: {{ .Values.aws.region }}
              - name: LIGHTWING_CLOUD-CONNECTOR_TYPE
                value: "harness"
              - name: LIGHTWING_CLOUD-CONNECTOR_REMOTE_HOST
                value: {{ .Values.global.loadbalancerURL }}
              - name: LIGHTWING_CLOUD-CONNECTOR_CONNECTOR_DETAILS_ROUTE
                value: ng/api/connectors/%s?accountIdentifier=%s
              - name: LIGHTWING_CLOUD-CONNECTOR_IDENTITY_SERVICE_SECRET
                value: HVSKUYqD4e5Rxu12hFDdCJKGM64sxgEynvdDhaOHaTHhwwn0K4Ttr0uoOxSsEVYNrUU=
              - name: LIGHTWING_CLOUD-CONNECTOR_AZURE_CLIENT_ID
                value: {{ .Values.azure.clientId }}
              - name: LIGHTWING_CLOUD-CONNECTOR_AZURE_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingCloudConnectorAzureClientSecret }}
              - name: LIGHTWING_CLOUD-CONNECTOR_REMOTE_API_TOKEN_SECRET
                value: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
              - name: LIGHTWING_METRICS_SEGMENT
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingMetricsSegment }}
              - name: LIGHTWING_GCPCOST_SVC_ACC_KEY_PATH
                value: "/opt/harness/svc/ce_batch_gcp_credentials.json"
              - name: LIGHTWING_GCPCOST_PROJECT
                value: {{ .Values.LIGHTWING_GCPCOST_PROJECT }}
              - name: LIGHTWING_AWS-GOV-MASTER_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingAwsGovmasterAccessKey }}
              - name: LIGHTWING_AWS-GOV-MASTER_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingAwsGovmasterSecretKey }}
            volumeMounts:
            - name: secret-mount
              mountPath: /opt/harness/svc
          volumes:
          - name: secret-mount
            secret:
              secretName: lwd-secret-mount
              items:
              - key: ce-batch-gcp-credentials
                path: ce_batch_gcp_credentials.json
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: lightwing-extract-coverage-{{ lower ( randAlphaNum 6 ) }}
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    {{- include "lwd.labels" . | nindent 4 }}
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      parallelism: 1
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: lightwing-extract-coverage
            image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
            command: ["lwd", "extract-coverage", "--verbose"]
            env:
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.postgresPassword.name }}
                    key: {{ .Values.postgresPassword.key }}
              - name: LIGHTWING_DB_CONNECTION
                value: "host=postgres.{{ .Release.Namespace }}.svc.cluster.local user=postgres password=$(DB_PASSWORD) dbname=postgres sslmode=disable"
              - name: FAKTORY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.faktoryPassword }}
              - name: FAKTORY_URL
                value: tcp://$(FAKTORY_PASSWORD):@lwd-faktory.{{ .Release.Namespace }}.svc.cluster.local:7419
              - name: LIGHTWING_CACHE_ADDR
                value: {{ .Values.redisUrl }}
              - name: LIGHTWING_AWSMASTER_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingAwsmasterAccessKey }}
              - name: LIGHTWING_AWSMASTER_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingAwsmasterSecretKey }}
              - name: LIGHTWING_AWSMASTER_REGION
                value: {{ .Values.aws.region }}
              - name: LIGHTWING_METRICS_SEGMENT
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingMetricsSegment }}
              - name: LIGHTWING_AWS-GOV-MASTER_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingAwsGovmasterAccessKey }}
              - name: LIGHTWING_AWS-GOV-MASTER_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.lwdSecrets.secretName }}
                    key: {{ .Values.lwdSecrets.lightwingAwsGovmasterSecretKey }}
          restartPolicy: Never
