apiVersion: batch/v1
kind: Job
metadata:
  name: lwd-migrate-{{ lower ( randAlphaNum 6 ) }}
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    {{- include "lwd.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: lwd-migrate
        {{- include "lwd.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: lwd
        image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
        command: ["lwd","migrate"]
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresPassword.name }}
                key: {{ .Values.postgresPassword.key }}
          - name: LIGHTWING_DB_CONNECTION
            value: "host=postgres.{{ .Release.Namespace }}.svc.cluster.local user=postgres password=$(DB_PASSWORD) dbname=postgres sslmode=disable"
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: lwd-{{ lower ( randAlphaNum 6 ) }}
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    {{- include "lwd.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lwd.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: lwd
        image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
        command: ["lwd","rebuild-search-index"]
        envFrom:
          - secretRef:
              name: lwd-secrets
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresPassword.name }}
                key: {{ .Values.postgresPassword.key }}
          - name: LIGHTWING_DB_CONNECTION
            value: "host=postgres.{{ .Release.Namespace }}.svc.cluster.local user=postgres password=$(DB_PASSWORD) dbname=postgres sslmode=disable"
          - name: FAKTORY_URL
            value: tcp://$(FAKTORY_PASSWORD):@lwd-faktory.{{ .Release.Namespace }}.svc.cluster.local:7419
          - name: LIGHTWING_CACHE_ADDR
            value: {{ .Values.redisUrl }}
          - name: LIGHTWING_CLOUD-CONNECTOR_TYPE
            value: "harness"
          - name: LIGHTWING_CLOUD-CONNECTOR_REMOTE_HOST
            value: {{ .Values.global.loadbalancerURL }}
          - name: LIGHTWING_CLOUD-CONNECTOR_CONNECTOR_DETAILS_ROUTE
            value: ng/api/connectors/%s?accountIdentifier=%s
          - name: LIGHTWING_CLOUD-CONNECTOR_CFT_PATH_ROUTE
            value: ng/api/connectors/getceawstemplateurl?accountIdentifier=%s
          - name: LIGHTWING_CLOUD-CONNECTOR_REMOTE_API_TOKEN_SECRET
            value: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
          - name: LIGHTWING_APIHOST
            value: {{ .Values.global.loadbalancerURL }}/lw/api
          - name: LIGHTWING_AWSMASTER_REGION
            value: {{ .Values.aws.region }}
          - name: LIGHTWING_CLOUD-CONNECTOR_IDENTITY_SERVICE_SECRET
            value: HVSKUYqD4e5Rxu12hFDdCJKGM64sxgEynvdDhaOHaTHhwwn0K4Ttr0uoOxSsEVYNrUU=
          - name: LIGHTWING_CLOUD-CONNECTOR_AZURE_CLIENT_ID
            value: {{ .Values.azure.clientId }}
          - name: LIGHTWING_GCPCOST_SVC_ACC_KEY_PATH
            value: "/opt/harness/svc/ce_batch_gcp_credentials.json"
          - name: LIGHTWING_GCPCOST_PROJECT
            value: {{ .Values.LIGHTWING_GCPCOST_PROJECT }}
      restartPolicy: Never
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
