apiVersion: v1
kind: Secret
metadata:
  name: lwd-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lwd.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "lwd.generateLwdSecrets" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: lwd-secret-mount
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lwd.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "lwd.generateMountSecrets" . }}
