apiVersion: v1
kind: Service
metadata:
  name: lwd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lwd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "lwd.selectorLabels" . | nindent 4 }}
