# Default values for anomaly-detection
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  loadbalancerURL: "https://test"
  ingress:
    enabled: false
    className: harness
    hosts:
      - my-host.example.org
    tls:
      enabled: true
      secretName: ''
# image pull secrets to use for every image
  imagePullSecrets: []

replicaCount: 1

maxSurge: 100%

maxUnavailable: 0

java:
  memory: "4096m"
  memoryLimit: "4096m"

image:
  registry: docker.io
  repository: harness/ce-anomaly-detection-signed
  pullPolicy: IfNotPresent
# Overrides the image tag whose default is the chart appVersion.
  tag: "70029"
  digest: ""
# image pull secrets to use for ce-anomaly-detection image
  imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "harness-default"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8081

ingress:
  className: nginx

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPU: ""
  targetMemory: ""

nodeSelector: {}

tolerations: []

affinity: {}

resources:
  limits:
    memory: "512Mi"
  requests:
    cpu: "512m"
    memory: "512Mi"

# extraVolumes:
#   - name: volume-test
#     configMap:
#       name: test-config
#       # readOnly: true
extraVolumes: []

# extraVolumeMounts:
#   - name: volume-test
#     mountPath: /opt/harness/config
extraVolumeMounts: []

lifecycleHooks: {}
# lifecycleHooks:
#   postStart:
#     exec:
#       command:
#   preStop:
#     exec:
#       command: