apiVersion: v1
kind: ConfigMap
metadata:
  name: dkron-server
  namespace: {{ .Release.Namespace }}
data:
  GODEBUG: 'netdns=go'
  DKRON_ENABLE_PROMETHEUS: 'false'
  dkron.yml: |+
    server: true
    bootstrap-expect: 1
    data-dir: /dkron/dkrondata
    retry-join: ["provider=k8s namespace={{.Release.namespace}} label_selector=\"app=dkron\""]
    log-level: debug
    serf-reconnect-timeout: 5s
    disable-usage-stats: true
