apiVersion: v2
name: ccm
description: A Helm chart for Harness Cloud Cost Management (CCM) module
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.6.4
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.546.0"
dependencies:
  - name: nextgen-ce
    version: 0.3.x
    repository: "file://../nextgen-ce"
  - name: event-service
    version: 0.3.x
    repository: "file://../event-service"
  - name: anomaly-detection
    version: 0.3.x
    repository: "file://../anomaly-detection"
  - name: cloud-info
    version: 0.3.x
    repository: "file://../cloud-info"
  - name: telescopes
    version: 0.3.x
    repository: "file://../telescopes"
  - name: batch-processing
    version: 0.3.x
    repository: "file://../batch-processing"
  - name: ng-ce-ui
    version: 0.3.x
    repository: "file://../ng-ce-ui"
  - name: clickhouse
    condition: clickhouse.enabled
    version: 2.1.0
    repository: https://charts.bitnami.com/bitnami
  - name: lwd-faktory
    condition: global.lwd.enabled
    version: 0.3.x
    repository: "file://../lightwingFaktory"
  - name: lwd
    condition: global.lwd.enabled
    version: 0.3.x
    repository: "file://../lightwingAPI"
  - name: lwd-worker
    condition: global.lwd.enabled
    version: 0.3.x
    repository: "file://../lightwingFaktoryWorker"
  - name: lwd-autocud
    condition: global.lwd.autocud.enabled
    version: 0.3.x
    repository: "file://../lightwingAutocud"
  - name: dkron
    condition: global.lwd.enabled
    version: 0.2.x
    repository: "file://../dkron"
