apiVersion: v1
kind: Service
metadata:
  name: ng-ce-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ng-ce-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
      name: http
  selector:
    {{- include "ng-ce-ui.selectorLabels" . | nindent 4 }}