apiVersion: v1
kind: Secret
metadata:
  name: batch-processing
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "batch-processing.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "batch-processing.generateSecrets" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: batch-processing-secret-mount
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "batch-processing.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "batch-processing.generateMountSecrets" . }}
