apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: anomaly-detection
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
   matchLabels:
    app: anomaly-detection
