apiVersion: v1
kind: Service
metadata:
  name: anomaly-detection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "anomaly-detection.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "anomaly-detection.selectorLabels" . | nindent 4 }}
