# Default values for nextgen-ce
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  loadbalancerURL: "https://test"
  ingress:
    enabled: false
    className: harness
    hosts:
      - my-host.example.org
    tls:
      enabled: true
      secretName: ''
  istio:
    enabled: false
    gateway:
      create: false
    virtualService:
      gateways:
      hosts:

replicaCount: 2

stackDriverLoggingEnabled: false

maxSurge: 100%

maxUnavailable: 0

java:
  memory: "4096m"
  memoryLimit: "4096m"

image:
  registry: docker.io
  repository: harness/ce-nextgen-signed
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "78300-000"
  digest: ""

imageClickhouseEnabled:
  registry: docker.io
  repository: harness/ce-nextgen-signed
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "9000363-000"
  digest: ""

waitForInitContainer:
  image:
    registry: docker.io
    repository: harness/helm-init-container
    pullPolicy: IfNotPresent
    tag: "latest"
    digest: ""

mongoSecrets:
  userName:
    name: harness-secrets
    key: mongodbUsername
  password:
    name: mongodb-replicaset-chart
    key: mongodb-root-password

timescaleSecret:
  password:
    name: harness-secrets
    key: timescaledbPostgresPassword

awsSecret:
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY: ""
  AWS_ACCOUNT_ID: ""
  AWS_DESTINATION_BUCKET: ""
  AWS_TEMPLATE_LINK: ""
  CE_AWS_TEMPLATE_URL: ""

ceng-gcp-credentials: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "harness-default"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 6340

ingress:
  className: nginx

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

cloudProviderConfig:
  GCP_PROJECT_ID: "placeHolder"
  AZURE_APP_CLIENT_ID: "0211763d-24fb-4d63-865d-92f86f77e908"
  AWS_GOV_CLOUD_ACCOUNT_ID: "147449478367"
  AWS_GOV_CLOUD_REGION_NAME: "us-gov-west-1"
  AWS_GOV_CLOUD_TEMPLATE_LINK: "https://continuous-efficiency.s3.us-east-2.amazonaws.com/setup/v1/ng/HarnessAWSTemplate.yaml"

clickhouse:
  enabled: false
  username: "default"
  password:
    name: clickhouse
    key: admin-password

resources:
  limits:
    cpu: 2
    memory: "5Gi"
  requests:
    cpu: 2
    memory: "5Gi"
