{{- if .Values.autoscaling.enabled }}
apiVersion: {{ include "harnesscommon.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  name: lwd-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lwd-worker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lwd-worker
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{ include "harnesscommon.hpa.metrics.apiVersion" . }}
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
  targetMemoryUtilizationPercentage : {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{ end }}
{{- end }}
