apiVersion: v1
kind: Secret
metadata:
  name: lwd-worker-secret-mount
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lwd-worker.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "lwd-worker.generateMountSecrets" . }}
