apiVersion: v1
kind: Secret
metadata:
  name: eventsvc-secret-mount
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "event-service.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "event-service.generateMountSecrets" . }}
