apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "event-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.port2 }}
      targetPort: event
      protocol: TCP
      name: event
  selector:
    {{- include "event-service.selectorLabels" . | nindent 4 }}
