# Default values for lwd
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  loadbalancerURL: "https://test"
  ingress:
    enabled: false
    className: harness
    hosts:
      - my-host.example.org
    tls:
      enabled: true
      secretName: ''
  istio:
    enabled: false
    gateway:
      create: false
    virtualService:
      gateways:
      hosts:
# image pull secrets to use for every image
  imagePullSecrets: []
  ccm:
    gcpProjectId: "placeHolder"
replicaCount: 2

maxSurge: 100%

maxUnavailable: 0

java:
  memory: "4096m"
  memoryLimit: "4096m"

image:
  registry: docker.io
  repository: harness/lightwing-signed
  pullPolicy: IfNotPresent
  tag: "main-1.1.1117"
  digest: ""
# image pull secrets to use for lightwing image
  imagePullSecrets: []

waitForInitContainer:
  image:
    registry: docker.io
    repository: harness/helm-init-container
    pullPolicy: IfNotPresent
    tag: "latest"
    digest: ""
  # image pull secrets to use for helm-init-container image
    imagePullSecrets: []

postgresPassword:
  name: postgres
  key: postgres-password

lwdSecrets:
  faktoryPassword: ""
  lightwingAwsmasterAccessKey: ""
  lightwingAwsmasterSecretKey: ""
  lightwingAwsGovmasterAccessKey: ""
  lightwingAwsGovmasterSecretKey: ""
  lightwingCloudConnectorAzureClientSecret: ""
  lightwingMetricsSegment: ""

ce-batch-gcp-credentials: ""

aws:
  region: "us-east-1"

azure:
  clientId: ""

redis:
  redisUrl: "redis://localhost:6379"
  useSentinel: "true"
  redisMaster: "harness-redis"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "harness-default"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9090

ingress:
  className: nginx

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPU: ""
  targetMemory: ""

nodeSelector: {}

tolerations: []

affinity: {}

resources:
  limits:
    cpu: 2
    memory: "4Gi"
  requests:
    cpu: 2
    memory: "4Gi"
