apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextgen-ce
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextgen-ce.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{.Values.maxSurge}}
      maxUnavailable: {{.Values.maxUnavailable}}
  selector:
    matchLabels:
      {{- include "nextgen-ce.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: nextgen-ce
        {{- include "nextgen-ce.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nextgen-ce.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      #waits only for mongo & timescale to start
      - name: wait-for-mongo
        image: {{ include "common.images.image" (dict "imageRoot" .Values.waitForInitContainer.image "global" .Values.global) }}
        imagePullPolicy: IfNotPresent
        args:
          - "pod"
          - "-lapp=mongodb-replicaset"
      - name: wait-for-timescale
        image: {{ include "common.images.image" (dict "imageRoot" .Values.waitForInitContainer.image "global" .Values.global) }}
        imagePullPolicy: IfNotPresent
        args:
          - "pod"
          - "-lapp=timescaledb-single-chart"
      containers:
        - name: nextgen-ce
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /ccm/api/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            failureThreshold: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ccm/api/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            failureThreshold: 10
            periodSeconds: 15
          envFrom:
            - configMapRef:
                name: nextgen-ce
            - secretRef:
                name: nextgen-ce
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongoSecrets.userName.name }}
                  key: {{ .Values.mongoSecrets.userName.key }}
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongoSecrets.password.name }}
                  key: {{ .Values.mongoSecrets.password.key }}
            - name: EVENTS_MONGO_DB_URL
              value: {{ include "harnesscommon.database.mongo" (dict "database" "events" "context" $) }}
            - name: NOTIFICATION_MONGO_URI
              value: {{ include "harnesscommon.database.mongo" (dict "database" "notification" "context" $) }}
            - name : TIMESCALEDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.timescaleSecret.password.name }}
                  key: {{ .Values.timescaleSecret.password.key }}
            - name : TIMESCALEDB_USERNAME
              value: postgres
            - name: TIMESCALEDB_URI
              value: 'jdbc:postgresql://timescaledb-single-chart.{{ .Release.Namespace }}:5432/harness'
            {{- if .Values.clickhouse.enabled }}
            - name : CLICKHOUSE_USERNAME
              value: {{ .Values.clickhouse.username | quote}}
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.clickhouse.password.name }}
                  key: {{ .Values.clickhouse.password.key }}
            {{- end }}
          volumeMounts:
          - name: secret-mount
            mountPath: /opt/harness/svc
      volumes:
      - name: secret-mount
        secret:
          secretName: ceng-secret-mount
          items:
          - key: ceng-gcp-credentials
            path: ceng_gcp_credentials.json
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nextgen-ce
            topologyKey: "kubernetes.io/hostname"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
