{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-info
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.global.ingress.className | quote }}
  rules:
    - http:
        paths:
          - backend:
              service:
                name: cloud-info
                port:
                  number: {{ .Values.service.port }}
            path: /ccm/public-pricing
            pathType: ImplementationSpecific
    {{- range .Values.global.ingress.hosts }}
      host: {{ . | quote }}
    {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.global.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}
{{- end }}
