apiVersion: v1
kind: Secret
metadata:
  name: cloud-info-secret-mount
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-info.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "cloud-info.generateMountSecrets" . }}
