apiVersion: v1
kind: Service
metadata:
  name: cloud-info
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-info.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "cloud-info.selectorLabels" . | nindent 4 }}
