apiVersion: v1
kind: Secret
metadata:
  name: lwd-autocud-secret-mount
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lwd-autocud.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "lwd-autocud.generateMountSecrets" . }}
