# Default values for batch-processing
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  loadbalancerURL: "https://test"
  ingress:
    enabled: false
    className: harness
    hosts:
      - my-host.example.org
    tls:
      enabled: true
      secretName: ''

replicaCount: 2

isolatedReplica: 2

java:
  memory: "7168"

image:
  registry: docker.io
  repository: harness/batch-processing-signed
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "77500"
  digest: ""

waitForInitContainer:
  image:
    registry: docker.io
    repository: harness/helm-init-container
    pullPolicy: IfNotPresent
    tag: "latest"
    digest: ""

mongoSecrets:
  userName:
    name: harness-secrets
    key: mongodbUsername
  password:
    name: mongodb-replicaset-chart
    key: mongodb-root-password

timescaleSecret:
  password:
    name: harness-secrets
    key: timescaledbPostgresPassword

smtp:
  host: ""
  password: ""
  user: ""

ceBatchGCPCredentials: ""

ceGCPHomeProjectCreds: ""

storageObjectAdmin: ""

awsSecret:
  S3_SYNC_CONFIG_ACCESSKEY: ""
  S3_SYNC_CONFIG_SECRETKEY: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "harness-default"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 6340

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

uiServerUrl: "https://app.harness.io"

GCP_PROJECT_ID: "placeHolder"

resources:
  limits:
    cpu: 1
    memory: "8192Mi"
  requests:
    cpu: 1
    memory: "8192Mi"
