apiVersion: v1
kind: ConfigMap
metadata:
  name: nextgen-ce
  namespace: {{ .Release.Namespace }}
data:
  LOGGING_LEVEL: "INFO"
  MANAGER_TARGET: "harness-manager:9879"
  MANAGER_AUTHORITY: "harness-manager:9879"
  MANAGER_CLIENT_BASEURL: "http://harness-manager.{{ .Release.Namespace }}.svc.cluster.local:9090/api/"
  NG_MANAGER_CLIENT_BASEURL: "http://ng-manager.{{ .Release.Namespace }}.svc.cluster.local:7090/"
  MANAGER_URL: "http://harness-manager.{{ .Release.Namespace }}.svc.cluster.local:9090/api/"
  DEPLOY_MODE: "KUBERNETES_ONPREM"
  CE_NEXTGEN_PORT: {{ .Values.service.port | quote}}
  EVENTS_FRAMEWORK_REDIS_URL: {{ include "harnesscommon.dbconnection.redisConnection" (dict "context" .Values.global.database.redis) }}
  EVENTS_FRAMEWORK_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME: "harness-redis"
  EVENTS_FRAMEWORK_REDIS_SENTINELS: {{ include "harnesscommon.dbconnection.redisConnection" (dict "context" .Values.global.database.redis) }}
  EVENTS_FRAMEWORK_ENV_NAMESPACE: ""
  EVENTS_FRAMEWORK_REDIS_SSL_ENABLED: "false"
  {{- if not .Values.workloadIdentity.enabled }}
  GOOGLE_CREDENTIALS_PATH: "/opt/harness/svc/ceng_gcp_credentials.json"
  GOOGLE_APPLICATION_CREDENTIALS: "/opt/harness/svc/ceng_gcp_credentials.json"
  CE_GCP_CREDENTIALS_PATH: "/opt/harness/svc/ceng_gcp_credentials.json"
  {{- end }}
  STACK_DRIVER_LOGGING_ENABLED: {{ .Values.global.stackDriverLoggingEnabled  | quote}}
  EVENTS_MONGO_INDEX_MANAGER_MODE: "AUTO"
  GCP_PROJECT_ID: {{ .Values.global.ccm.gcpProjectId  | quote}}
  AZURE_APP_CLIENT_ID: {{ .Values.cloudProviderConfig.AZURE_APP_CLIENT_ID  | quote}}
  AZURE_ENABLE_FILE_CHECK_AT_SOURCE: "true"
  AWS_GOV_CLOUD_ACCOUNT_ID: {{ .Values.cloudProviderConfig.AWS_GOV_CLOUD_ACCOUNT_ID  | quote}}
  AWS_GOV_CLOUD_TEMPLATE_LINK: {{ .Values.cloudProviderConfig.AWS_GOV_CLOUD_TEMPLATE_LINK  | quote}}
  AWS_GOV_CLOUD_REGION_NAME: {{ .Values.cloudProviderConfig.AWS_GOV_CLOUD_REGION_NAME  | quote}}
  SEGMENT_ENABLED: "false"
  AUDIT_ENABLED: "true"
  AUDIT_CLIENT_BASEURL: "http://platform-service.{{ .Release.Namespace }}.svc.cluster.local:9005/api/"
  NOTIFICATION_BASE_URL: "http://platform-service.{{ .Release.Namespace }}.svc.cluster.local:9005/api/"
  ACCESS_CONTROL_BASE_URL: "http://access-control.{{ .Release.Namespace }}.svc.cluster.local:9006/api/"
  ACCESS_CONTROL_ENABLED: "true"
  MOCK_ACCESS_CONTROL_SERVICE: "false"
  MEMORY: {{ .Values.java.memory | quote }}
  ENABLE_APPDYNAMICS: "false"
  JWT_AUTH_SECRET: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
  NEXT_GEN_MANAGER_SECRET: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
  JWT_IDENTITY_SERVICE_SECRET: HVSKUYqD4e5Rxu12hFDdCJKGM64sxgEynvdDhaOHaTHhwwn0K4Ttr0uoOxSsEVYNrUU=
  NOTIFICATION_CLIENT_SECRET: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
  ACCESS_CONTROL_SECRET: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
  CLICKHOUSE_ENABLED: {{ .Values.clickhouse.enabled | quote }}
  {{- if .Values.clickhouse.enabled }}
  CLICKHOUSE_URL: "jdbc:ch://clickhouse.{{ .Release.Namespace }}.svc.cluster.local:8123"
  {{- end }}
  USE_WORKLOAD_IDENTITY: {{ .Values.workloadIdentity.enabled | quote }}
  GCP_SERVICE_ACCOUNT_EMAIL: {{ .Values.cloudProviderConfig.GCP_SERVICE_ACCOUNT_EMAIL | quote }}
  {{- if .Values.global.proxy.enabled }}
  PROXY_ENABLED: '{{ .Values.global.proxy.enabled }}'
  PROXY_HOST: {{ .Values.global.proxy.host }}
  PROXY_PORT: '{{ .Values.global.proxy.port }}'
  PROXY_USERNAME: '{{ .Values.global.proxy.username }}'
  PROXY_PASSWORD: '{{ .Values.global.proxy.password }}'
  PROXY_PROTOCOL: {{ .Values.global.proxy.protocol }}
  {{- end }}
  {{- if .Values.global.awsServiceEndpointUrls.enabled }}
  AWS_SERVICE_ENDPOINT_URLS_ENABLED: '{{ .Values.global.awsServiceEndpointUrls.enabled }}'
  AWS_SERVICE_ENDPOINT_URLS_ENDPOINT_REGION: {{ .Values.global.awsServiceEndpointUrls.endPointRegion }}
  AWS_SERVICE_ENDPOINT_URLS_S3_ENDPOINT_URL: {{ .Values.global.awsServiceEndpointUrls.s3EndPointUrl }}
  AWS_SERVICE_ENDPOINT_URLS_STS_ENDPOINT_URL: {{ .Values.global.awsServiceEndpointUrls.stsEndPointUrl }}
  AWS_SERVICE_ENDPOINT_URLS_EC2_ENDPOINT_URL: {{ .Values.global.awsServiceEndpointUrls.ec2EndPointUrl }}
  AWS_SERVICE_ENDPOINT_URLS_ECS_ENDPOINT_URL: {{ .Values.global.awsServiceEndpointUrls.ecsEndPointUrl }}
  AWS_SERVICE_ENDPOINT_URLS_CLOUDWATCH_ENDPOINT_URL: {{ .Values.global.awsServiceEndpointUrls.cloudwatchEndPointUrl }}
  {{- end }}
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
