apiVersion: v1
kind: ConfigMap
metadata:
  name: nextgen-ce
  namespace: {{ .Release.Namespace }}
data:
  LOGGING_LEVEL: "INFO"
  MANAGER_TARGET: "harness-manager:9879"
  MANAGER_AUTHORITY: "harness-manager:9879"
  MANAGER_CLIENT_BASEURL: "http://harness-manager.{{ .Release.Namespace }}.svc.cluster.local:9090/"
  NG_MANAGER_CLIENT_BASEURL: "http://ng-manager.{{ .Release.Namespace }}.svc.cluster.local:7090/"
  MANAGER_URL: "http://harness-manager.{{ .Release.Namespace }}.svc.cluster.local:9090/"
  DEPLOY_MODE: "KUBERNETES_ONPREM"
  CE_NEXTGEN_PORT: {{ .Values.service.port | quote}}
  EVENTS_FRAMEWORK_REDIS_URL: "redis://localhost:6379"
  EVENTS_FRAMEWORK_USE_SENTINEL: "true"
  EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME: "harness-redis"
  EVENTS_FRAMEWORK_REDIS_SENTINELS: "redis://redis-sentinel-harness-announce-0.{{ .Release.Namespace }}:26379,redis://redis-sentinel-harness-announce-1.{{ .Release.Namespace }}:26379,redis://redis-sentinel-harness-announce-2.{{ .Release.Namespace }}:26379"
  EVENTS_FRAMEWORK_ENV_NAMESPACE: {{ .Release.Namespace }}
  EVENTS_FRAMEWORK_REDIS_SSL_ENABLED: "false"
  GOOGLE_CREDENTIALS_PATH: "/opt/harness/svc/ceng_gcp_credentials.json"
  GOOGLE_APPLICATION_CREDENTIALS: "/opt/harness/svc/ceng_gcp_credentials.json"
  CE_GCP_CREDENTIALS_PATH: "/opt/harness/svc/ceng_gcp_credentials.json"
  STACK_DRIVER_LOGGING_ENABLED: "false"
  EVENTS_MONGO_INDEX_MANAGER_MODE: "MANUAL"
  GCP_PROJECT_ID: {{ .Values.GCP_PROJECT_ID  | quote}}
  AZURE_APP_CLIENT_ID: "0211763d-24fb-4d63-865d-92f86f77e908" ##TODO
  AZURE_ENABLE_FILE_CHECK_AT_SOURCE: "true"
  AWS_GOV_CLOUD_ACCOUNT_ID: "147449478367" #TODO
  AWS_GOV_CLOUD_TEMPLATE_LINK: "https://continuous-efficiency.s3.us-east-2.amazonaws.com/setup/v1/ng/HarnessAWSTemplate.yaml" #TODO
  AWS_GOV_CLOUD_REGION_NAME: "us-gov-west-1" #TODO
  SEGMENT_ENABLED: "false"
  AUDIT_ENABLED: "true"
  AUDIT_CLIENT_BASEURL: "http://platform-service.{{ .Release.Namespace }}.svc.cluster.local:9005/api/"
  NOTIFICATION_BASE_URL: "http://platform-service.{{ .Release.Namespace }}.svc.cluster.local:9005/api/"
  ACCESS_CONTROL_BASE_URL: "http://access-control.{{ .Release.Namespace }}.svc.cluster.local:9006/api/"
  ACCESS_CONTROL_ENABLED: "true"
  MOCK_ACCESS_CONTROL_SERVICE: "false"
  MEMORY: {{ .Values.java.memory | quote }}
  ENABLE_APPDYNAMICS: "false"
  JWT_AUTH_SECRET: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
  NEXT_GEN_MANAGER_SECRET: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
  JWT_IDENTITY_SERVICE_SECRET: HVSKUYqD4e5Rxu12hFDdCJKGM64sxgEynvdDhaOHaTHhwwn0K4Ttr0uoOxSsEVYNrUU=
  NOTIFICATION_CLIENT_SECRET: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
  ACCESS_CONTROL_SECRET: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
